---
abstract: 'The authentication middeleware collection for Plack.'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Doorman
name: Doorman
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  IO::Socket::SSL: 1.39
  LWPx::ParanoidAgent: 1.07
  Net::OpenID::Consumer: 1.03
  Net::Twitter::Lite: 1.03
requires:
  Plack: 0.9963
  Plack::Middleware::Session: 0.13
  perl: 5.10.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.07
